// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtJe48vQbmZAXAUkFTVkS0b-4DPaN3C48',
    appId: '1:652043719656:web:de6af74aedde80e5864a5d',
    messagingSenderId: '652043719656',
    projectId: 'f-bmi-tracker',
    authDomain: 'f-bmi-tracker.firebaseapp.com',
    storageBucket: 'f-bmi-tracker.firebasestorage.app',
    measurementId: 'G-BVM58QFWCE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuoae7o8NAnuXmAhUAJijMZ61uKzoy9mo',
    appId: '1:652043719656:android:3325f30f19df6e48864a5d',
    messagingSenderId: '652043719656',
    projectId: 'f-bmi-tracker',
    storageBucket: 'f-bmi-tracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT0aH2Eu58Fx_02cAav86b2wQyk7XBYCA',
    appId: '1:652043719656:ios:ad7c803ed70c752e864a5d',
    messagingSenderId: '652043719656',
    projectId: 'f-bmi-tracker',
    storageBucket: 'f-bmi-tracker.firebasestorage.app',
    iosBundleId: 'com.example.fBmiTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAT0aH2Eu58Fx_02cAav86b2wQyk7XBYCA',
    appId: '1:652043719656:ios:ad7c803ed70c752e864a5d',
    messagingSenderId: '652043719656',
    projectId: 'f-bmi-tracker',
    storageBucket: 'f-bmi-tracker.firebasestorage.app',
    iosBundleId: 'com.example.fBmiTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtJe48vQbmZAXAUkFTVkS0b-4DPaN3C48',
    appId: '1:652043719656:web:3c3e0aaa8e203e78864a5d',
    messagingSenderId: '652043719656',
    projectId: 'f-bmi-tracker',
    authDomain: 'f-bmi-tracker.firebaseapp.com',
    storageBucket: 'f-bmi-tracker.firebasestorage.app',
    measurementId: 'G-2Y3FEB7BCF',
  );
}
